### ISSUE TITLE
Migrate to kde-mac organization.

### ISSUE THREAD

**Issue by yurikoles** [KDE-mac/homebrew-kf5#147]
@haraldF could you please redirect this repo to [kde-mac/homebrew-kf5](/kde-mac/homebrew-kf5)?

**Comment by krf** [comment]
Two questions:
a) Who's the owner of that new org? https://github.com/orgs/KDE-mac/people lists no people
b) What do you mean with 'redirect'?

@haraldF I'll let you handle that, since you're the original owner of this repository here.

**Comment by RichardsonAlex** [comment]
Since the repository already exists this won't work properly. The only way of doing this would be for @haraldF to go to the settings for this repository and do `Transfer ownership`. This way all the issues are also transferred to the new repository instead of it just being a mirror of the code. Also all clones of the old URL will be redirected to the new one.

**Comment by haraldF** [comment]
I tried to do that, but got: "You don’t have the permission to create repositories on KDE-mac"

**Comment by RichardsonAlex** [comment]
Ah I think you can only transfer ownership to organizations where you are a member.

**Comment by haraldF** [comment]
I am a member, and I should have push rights. But it seems I also need the 'create repositories' permission?

**Comment by yurikoles** [comment]
@haraldF I had added you as owner just now.

**Comment by haraldF** [comment]
@yurikoles - grr... still getting "You don’t have the permission to create repositories on KDE-mac", what am I doing wrong...???

**Comment by haraldF** [comment]
@yurikoles - ok, I had to "accept" your invitation first. Now getting `Moving repository to KDE-mac/homebrew-kf5. This may take a few minutes.`

**Comment by haraldF** [comment]
Seems it worked :) Ownership is transferred.

**Comment by yurikoles** [comment]
@sl1pkn07 please resend your patches, because I had merge conflicts.

**Comment by sl1pkn07** [comment]
Sorry for the mess i make yesterday :S

When i go to home i'll summit the changes

Btw. Any git manual for dummies? Existing manuals i see is little complicated for me

Greetings

**Comment by sl1pkn07** [comment]
i can't create a branch with my changes (or can't access to it)

pushed it on master?

seems need garbage collector (?) on the repo

greetings

**Comment by yurikoles** [comment]
I had fixed issue with branches by creating fresh clone of repo instead of using brew's one.

**Comment by sl1pkn07** [comment]
I'm don't use brew, use my linux machine (my main rig)
